apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress-new
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /nginxserver
        pathType: Prefix
        backend:
          service:
            name: nginx
            port: 
              number: 80
