kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: only-allow-from-busybox-secure-ns
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: web
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          type: secure
      podSelector:
        matchLabels:
          type: monitoring
