apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: sslconfigs.stable.example.com
spec:
  group: stable.example.com
  versions: 
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              cert:
                type: string
              key:
                type: string
              domain:
                type: string
  scope: Namespaced
  names:
    plural: sslconfigs
    singular: sslconfig
    kind: SslConfig
    shortNames:
    - ssl
